/**
 * NexoWatt Quellcode-Erklärung (DE)
 * Aufgabe: Führt Installer/Admin durch Master-, Slave-, Grenz- und Paarungseinstellungen.
 * Daten und Wirkung: Liest geschützte Diagnosen und speichert geprüfte Konfigurationen. Paarungsschlüssel bleiben nur vorübergehend im Formular, niemals im Browser-Speicher.
 * Bei Änderungen: Rollen, 99-Knoten-Limit, Nullgrenzen und Backend-Prüfungen gemeinsam testen.
 * Verknüpfungen: docs/quellcode/src-admin-tab/src/pages/MeshCoordinatorPage.md
 * Einstieg: docs/QUELLCODE_WEGWEISER_DE.md; Pflege: docs/DOKUMENTATIONSSTANDARD_DE.md
 */
import React, { useEffect, useState } from 'react';
import PageShell from './PageShell';
import MeshAccountingPanel from './MeshAccountingPanel';
import { meshCoordinatorRequest } from '../lib/adminConnection';
const labels = { importW: 'Hausbezug W', exportW: 'Einspeisung W', l1A: 'Phase L1 A', l2A: 'Phase L2 A', l3A: 'Phase L3 A', evW: 'Ladepunkte gesamt W', chargeW: 'Speicherladung W', dischargeW: 'Speicherentladung W', pvW: 'PV-Erzeugung W', flexW: 'Weitere flexible Lasten W' };
const zeros = () => Object.fromEntries(Object.keys(labels).map(key => [key, 0]));
const blankNode = id => ({ id, name: '', branch: '', max: zeros(), fallback: zeros(), weight: 1, commissioned: false, watchdogVerified: false });
function NumberField({ label, value, onChange }) { return <label className="nw-field-label">{label}<input className="nw-input" type="number" min="0" step="any" value={value ?? 0} onChange={e => onChange(e.target.value === '' ? '' : Number(e.target.value))} required /></label>; }
function GroupLimits({ value, onChange }) {
  return <div style={{ overflowX: 'auto' }}><table style={{ width: '100%' }}><thead><tr><th>Grenze</th><th>Anschluss</th><th>Reserve</th><th>Nicht erfasste Last</th></tr></thead><tbody>{Object.keys(value.limit).map(key => <tr key={key}><th>{labels[key]}</th>{['limit', 'reserve', 'unmonitored'].map(field => <td key={field}><NumberField label={`${field} ${labels[key]}`} value={value[field][key]} onChange={n => onChange({ ...value, [field]: { ...value[field], [key]: n } })} /></td>)}</tr>)}</tbody></table></div>;
}
function NodeEditor({ value, onChange, local = false }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  return <div style={{ display: 'grid', gap: 12 }}>
    {!local && <label className="nw-field-label">Eindeutige Slave-ID<input className="nw-input" value={value.id} onChange={e => set('id', e.target.value)} required pattern="[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}" /></label>}
    <label className="nw-field-label">Haus / Gerät<input className="nw-input" value={value.name} onChange={e => set('name', e.target.value)} /></label>
    <label className="nw-field-label">Strang-ID (optional)<input className="nw-input" value={value.branch} onChange={e => set('branch', e.target.value)} /></label>
    <NumberField label="Verteilungsgewicht (1–100)" value={value.weight} onChange={n => set('weight', n)} />
    <div style={{ overflowX: 'auto' }}><table style={{ width: '100%' }}><thead><tr><th>Gesamtes Haus</th><th>Maximum</th><th>Sicherer Rückfall</th></tr></thead><tbody>{Object.keys(labels).map(key => <tr key={key}><th>{labels[key]}</th>{['max', 'fallback'].map(field => <td key={field}><NumberField label={`${field === 'max' ? 'Maximum' : 'Rückfall'} ${labels[key]}`} value={value[field][key]} onChange={n => set(field, { ...value[field], [key]: n })} /></td>)}</tr>)}</tbody></table></div>
    <label><input type="checkbox" checked={value.commissioned} onChange={e => set('commissioned', e.target.checked)} /> Lokale Messung, Vorzeichen, Gerätegrenzen und Regelung geprüft</label>
    <label><input type="checkbox" checked={value.watchdogVerified} onChange={e => set('watchdogVerified', e.target.checked)} /> Unabhängigen Geräte-Rückfall bei EOS-/Verbindungsausfall vor Ort nachgewiesen</label>
  </div>;
}
/** Lokales Bearbeiten und regelmäßige Statusabfrage sind getrennt: Polling darf
 * keine ungespeicherten Grenzwerte überschreiben. Aktive Konfiguration ist gesperrt. */
export default function MeshCoordinatorPage() {
  const [app, setApp] = useState(null); const [unavailable, setUnavailable] = useState(false);
  const [config, setConfig] = useState(null); const [status, setStatus] = useState(null); const [selected, setSelected] = useState(0);
  const [message, setMessage] = useState('Konfiguration wird geladen…'); const [busy, setBusy] = useState(false); const [locked, setLocked] = useState(false);
  const [pairingKey, setPairingKey] = useState(''); const [bundle, setBundle] = useState(''); const [importBundle, setImportBundle] = useState(''); const [paired, setPaired] = useState([]);
  useEffect(() => {
    let mounted = true; let timer;
    const poll = async (first = false) => { try { const data = await meshCoordinatorRequest(); if (!mounted) return; setApp(data.app); setUnavailable(false); setStatus(data.status); setLocked(data.locked || data.config.mode === 'active'); setPaired(data.pairedNodes); if (first) { setConfig(data.config); setMessage('Verbindung zuerst im Diagnosebetrieb einrichten.'); } else setConfig(previous => previous === null || data.config.mode === 'active' ? data.config : previous); } catch (error) { if (mounted) { setMessage(error.message); if ([401, 403, 404].includes(Number(error.status))) { setUnavailable(true); setConfig(null); setStatus(null); setBundle(''); } } } finally { if (mounted) timer = setTimeout(() => poll(), 2000); } };
    poll(true); return () => { mounted = false; clearTimeout(timer); };
  }, []);
  const update = (key, value) => setConfig(previous => ({ ...previous, [key]: value }));
  const save = async event => {
    event.preventDefault(); setBusy(true); setBundle('');
    try { const data = await meshCoordinatorRequest('/config', { config, pairingKey }); setConfig(data.config); setLocked(data.config.mode === 'active'); setPairingKey(''); setPaired(data.pairedNodes); setMessage('Konfiguration gespeichert. Aktive Verbünde starten mit sicherem Rückfall und neuer Synchronisation.'); }
    catch (error) { setMessage(error.message); } finally { setBusy(false); }
  };
  const pair = async () => { setBusy(true); try { const data = await meshCoordinatorRequest('/pair', { nodeId: config.nodes[selected].id }); setBundle(JSON.stringify(data, null, 2)); setMessage('Paarungsdaten einmalig kopieren und am zugehörigen Slave importieren. Vertraulich behandeln.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const loadBundle = () => { try { const data = JSON.parse(importBundle); if (data.config?.role !== 'slave' || !data.pairingKey) throw new Error('Slave-Paarungsdaten fehlen.'); setConfig(data.config); setPairingKey(data.pairingKey); setImportBundle(''); setMessage('Paarung übernommen. Master-Adresse und lokale Messwerte ergänzen, anschließend speichern.'); } catch (error) { setMessage(error.message); } };
  return <PageShell title="Microgrid · Master / Slave" subtitle="EMS-App · Ein Trafo-Master · bis zu 99 Haus-Slaves" showBack={false} compact={new URLSearchParams(window.location.search).has('embedded')} actions={<a className="nw-link-button" href="/ems-apps.html?nwAdmin=1" target={window.parent !== window ? '_parent' : '_self'}>Zum EMS-AppCenter</a>}>
    {unavailable && <section className="nw-card"><p role="alert">{message}</p><p>Die App muss im EMS-AppCenter installiert sein. Zugriff nur für Installer und Admin.</p></section>}
    {!unavailable && <>
    {app && !app.enabled && <section className="nw-card"><strong>App inaktiv</strong><p>Einrichtung und gespeicherte Daten sind zugänglich. Regelkommunikation und Zähleraufzeichnung starten erst mit „Aktiv: An“ im EMS-AppCenter.</p></section>}
    <section className="nw-card"><h2>Verbindung und Freigaben</h2><p role="status">{message}</p>{status && <><p><strong>{status.master?.controlMode === 'LOCAL_AUTONOMY' ? 'Lokale Hausregelung' : status.master?.controlMode === 'TRANSFORMER_LIMIT' ? 'Trafo-Begrenzung' : status.master?.state || status.local?.state}</strong> · Antwort {status.timing.lastRttMs === null ? '—' : `${Math.round(status.timing.lastRttMs)} ms`} · P95 {status.timing.p95RttMs === null ? '—' : `${Math.round(status.timing.p95RttMs)} ms`} · Freigabe {Math.round(status.local?.remainingMs || 0)} ms</p><p>{status.master?.reason || status.local?.reason} {status.error}</p>{status.master?.siteMeasurement && <p>Trafo-NVP: {Number.isFinite(status.master.siteMeasurement.gridW) ? `${Math.round(status.master.siteMeasurement.gridW)} W` : 'Messung fehlt'} · Messwertalter: {Number.isFinite(status.master.siteMeasurement.ageMs) ? `${Math.round(status.master.siteMeasurement.ageMs)} ms` : '—'} · Phasen A: {status.master.siteMeasurement.phaseA?.map(n => Number(n).toFixed(1)).join(' / ') || '—'}</p>}</>}
      <p>Der Master begrenzt den gesamten Hausanschluss. 0 ist eine wirksame Grenze. Bei Ausfall bleibt nur der geplante Rückfall; Boost und Zeitpläne erhöhen ihn nicht.</p>
      <p>Direkte Tailscale-Verbindungen bevorzugen; tatsächliche Laufzeit am Standort prüfen. Ein unabhängiger Geräte-Watchdog ist für aktive Regelung erforderlich.</p>
      {locked && <p><strong>Aktive Konfiguration geschützt.</strong> Grenz- oder Topologieänderungen benötigen eine geplante Stillsetzung und erneute Inbetriebnahme.</p>}
    </section>
    {status?.master && <section className="nw-card"><h2>Betreiberübersicht · Teilnehmer ({status.master.nodes.length}/100 einschließlich optionalem Master-Haus)</h2><div style={{ overflowX: 'auto', maxHeight: 360 }}><table style={{ width: '100%' }}><thead><tr><th>Haus</th><th>Verbindung</th><th>Alter</th><th>Antwortzeit</th><th>Bestätigt</th><th>Haus-NVP aktuell</th><th>Bezug / Reserviert</th><th>Einspeisegrenze</th></tr></thead><tbody>{status.master.nodes.map(node => <tr key={node.id}><td>{node.name || node.id}</td><td>{node.online ? 'Verbunden' : 'Fehlt'}</td><td>{node.ageMs === null ? '—' : `${Math.round(node.ageMs)} ms`}</td><td>{node.rttMs === null ? '—' : `${Math.round(node.rttMs)} ms`}</td><td>{node.confirmed ? 'Verifiziert' : 'Ausstehend'}</td><td>{Number.isFinite(node.sample?.gridW) ? `${Math.round(node.sample.gridW)} W` : '—'}</td><td>{Math.round(node.allowed.importW)} / {Math.round(node.reserved.importW)} W</td><td>{Math.round(node.allowed.exportW)} W</td></tr>)}</tbody></table></div></section>}
    {config && config.role !== 'off' && <MeshAccountingPanel meshConfig={config} status={status} />}
    {config && <form onSubmit={save}><fieldset disabled={busy || locked} style={{ border: 0, padding: 0, minWidth: 0 }}>
      <section className="nw-card" style={{ display: 'grid', gap: 14 }}><h2>Verbund einrichten</h2>
        <label className="nw-field-label">Rolle<select className="nw-input" value={config.role} onChange={e => update('role', e.target.value)}><option value="off">Aus</option><option value="master">Master</option><option value="slave">Slave</option></select></label>
        {config.role !== 'off' && <>
          {['siteId', 'nodeId', 'masterId'].map((key, index) => <label className="nw-field-label" key={key}>{['Standort-ID', 'Lokale Knoten-ID', 'Feste Master-ID'][index]}<input className="nw-input" value={config[key]} onChange={e => update(key, e.target.value)} required /></label>)}
          <NumberField label="Gemeinsame Konfigurationsversion" value={config.revision} onChange={n => update('revision', n)} />
          <label className="nw-field-label">Betrieb<select className="nw-input" value={config.mode} onChange={e => update('mode', e.target.value)}><option value="diagnostic">Diagnose – noch keine Master-Regelung</option><option value="active">Aktiv – geprüfte Anlage verbindlich begrenzen</option></select></label>
          {config.role === 'slave' && <><label className="nw-field-label">Tailscale-Adresse des Masters inklusive EOS-Port<input className="nw-input" placeholder="http://100.x.x.x:8188" value={config.masterUrl} onChange={e => update('masterUrl', e.target.value)} required /></label><label className="nw-field-label">Individueller Paarungsschlüssel<input className="nw-input" type="password" autoComplete="new-password" value={pairingKey} onChange={e => setPairingKey(e.target.value)} placeholder="Leer lassen zum Beibehalten" /></label></>}
          {config.role === 'master' && <label><input type="checkbox" checked={config.localParticipates} onChange={e => update('localParticipates', e.target.checked)} /> Master regelt zusätzlich sein eigenes Haus</label>}
          <details><summary>Kommunikationszeiten und Wiederanlauf</summary><p>Startwerte: Austausch 1 s, Antwort-Timeout 800 ms, Freigabe 3 s, Messwertalter höchstens 2 s. Vor Ort prüfen.</p>{[['intervalMs','Austausch ms'],['requestTimeoutMs','Antwort-Timeout ms'],['leaseMs','Freigabedauer ms'],['staleMs','Maximales Messwertalter ms'],['recoveryCycles','Stabile Zyklen vor Erhöhung'],['rampWPerSecond','Wiederanlauframpe W/s']].map(([key,label]) => <NumberField key={key} label={label} value={config[key]} onChange={n => update(key,n)} />)}</details>
        </>}
      </section>
      {config.role === 'master' && <>
        <section className="nw-card"><h2>Trafo-Regelung</h2><label className="nw-field-label">Verteilung<select className="nw-input" value={config.allocation?.strategy || 'fixed'} onChange={e => update('allocation', { ...(config.allocation || { headroomW: 1000, headroomA: 3, engagePct: 90, releasePct: 80 }), strategy: e.target.value })}><option value="fixed">Feste Anteile (bisheriges Verhalten)</option><option value="transformer">Bedarfsabhängig · Master am Trafo, Slaves an Häusern</option></select></label><p>Die Häuser optimieren lokal innerhalb sicherer NVP-Korridore. Bei knapper Kapazität verteilt der Master die Gesamtfreigabe bedarfsgerecht. Haus- und Stranggrenzen gelten in jedem Betriebszustand.</p>{config.allocation?.strategy === 'transformer' && <>{[['headroomW','Zusätzlicher Spielraum je Haus W'],['headroomA','Zusätzlicher Spielraum je Phase A'],['engagePct','Eingriff ab Trafoauslastung %'],['releasePct','Wiederfreigabe unter Trafoauslastung %']].map(([k,label]) => <NumberField key={k} label={label} value={config.allocation[k]} onChange={n => update('allocation', { ...config.allocation, [k]: n })} />)}<button className="nw-button" type="button" onClick={() => setConfig(p => ({ ...p, intervalMs: 250, requestTimeoutMs: 200, leaseMs: 1500, staleMs: 1000 }))}>Schnellen Takt übernehmen: 250 ms / 200 ms Timeout</button><p>Nur bei entsprechend schnellen NVP-Messwerten und stabiler Verbindung verwenden. Messung, Netzwerk und Stellgeräte bestimmen zusammen die tatsächliche Reaktionszeit.</p></>}</section>
        <section className="nw-card"><h2>Gemeinsamer Anschluss</h2><p>Hauptzähler und alle drei Phasen unter der lokalen Netzmessung zuordnen. Für nicht geregelte Lasten dauerhaft Kapazität vorhalten.</p><GroupLimits value={config.site} onChange={next => update('site', next)} />{config.localParticipates && <><h3>Getrennter Hauptzähler des Verbunds</h3><p>Hier die Messung des gesamten Standorts eintragen; die lokale Hausmessung bleibt getrennt.</p>{['gridW','l1A','l2A','l3A'].map(key=><label className="nw-field-label" key={key}>{key} – Hauptzähler-DP<input className="nw-input" value={config.siteFeedback?.[key] || ''} onChange={e=>update('siteFeedback',{...config.siteFeedback,[key]:e.target.value})} /></label>)}</>}</section>
        <section className="nw-card"><h2>Stränge</h2>{config.branches.map((branch,i) => <details key={i}><summary>Strang {branch.id || i+1}</summary><input className="nw-input" aria-label="Strang-ID" value={branch.id} onChange={e => update('branches',config.branches.map((b,j)=>i===j?{...b,id:e.target.value}:b))} /><GroupLimits value={branch} onChange={next => update('branches',config.branches.map((b,j)=>i===j?next:b))} /><button className="nw-button" type="button" onClick={()=>update('branches',config.branches.filter((_,j)=>j!==i))}>Strang entfernen</button></details>)}<button className="nw-button" type="button" onClick={()=>update('branches',[...config.branches,{id:'',...JSON.parse(JSON.stringify(config.site)),limit:Object.fromEntries(Object.keys(config.site.limit).map(k=>[k,0]))}])}>Strang hinzufügen</button></section>
        <section className="nw-card"><h2>Slaves ({config.nodes.length}/99)</h2><p>Erst Teilnehmer speichern, dann für jeden Slave eigene Paarungsdaten erzeugen.</p><select className="nw-input" aria-label="Slave auswählen" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{config.nodes.map((n,i)=><option key={i} value={i}>{n.name || n.id || `Slave ${i+1}`} {paired.includes(n.id)?'· gepaart':''}</option>)}</select>
          {config.nodes[selected] && <><NodeEditor value={config.nodes[selected]} onChange={next => update('nodes',config.nodes.map((n,i)=>i===selected?next:n))} /><button className="nw-button" type="button" onClick={pair}>Paarung für gespeicherten Slave erzeugen</button><button className="nw-button" type="button" onClick={()=>{update('nodes',config.nodes.filter((_,i)=>i!==selected));setSelected(0);setBundle('');}}>Slave entfernen</button></>}
          <button className="nw-button" type="button" disabled={config.nodes.length>=99} onClick={()=>{update('nodes',[...config.nodes,blankNode(`haus_${config.nodes.length+1}`)]);setSelected(config.nodes.length);setBundle('');}}>Slave hinzufügen</button>
        </section>
      </>}
      {(config.role === 'slave' || (config.role === 'master' && config.localParticipates)) && <section className="nw-card"><h2>Lokales Haus</h2><NodeEditor local value={config.local} onChange={next=>update('local',next)} /><h3>Tatsächliche Leistungen</h3><p>Summenmesswerte in W, jeweils positiv. Nur vorhandene Geräte freigeben. Lokalen NVP und Phasen im App-Center zuordnen.</p>{['evW','chargeW','dischargeW','pvW','flexW'].map(key=><label className="nw-field-label" key={key}>{labels[key]} – Messwert-DP<input className="nw-input" value={config.feedback?.[key] || ''} onChange={e=>update('feedback',{...config.feedback,[key]:e.target.value})} /></label>)}</section>}
      <section className="nw-card"><button className="nw-button nw-button--primary" type="submit">Konfiguration speichern</button></section>
      {config.role !== 'master' && <section className="nw-card"><h2>Paarung vom Master übernehmen</h2><textarea className="nw-input" rows={5} aria-label="Paarungsdaten importieren" value={importBundle} onChange={e=>setImportBundle(e.target.value)} /><button className="nw-button" type="button" onClick={loadBundle}>Paarung in Formular übernehmen</button></section>}
    </fieldset></form>}
    {bundle && <section className="nw-card"><h2>Einmalige Paarungsdaten</h2><p>Enthält den Schlüssel dieses Slaves. Nach Übernahme schließen.</p><textarea className="nw-input" rows={8} readOnly value={bundle} aria-label="Einmalige Paarungsdaten" /><button className="nw-button" onClick={()=>setBundle('')}>Schließen und aus Ansicht entfernen</button></section>}
    </>}
  </PageShell>;
}
