'use strict';
// Never include error.message, request/response objects or unbounded properties.
function probeFailure(error, port) {
    return { code: error?.code === 'ONBOARD_HTTPS_NOT_READY' ? 'ONBOARD_HTTPS_NOT_READY' : 'MANAGEMENT_PROBE_FAILED',
        stage: error?.stage === 'https-probe' ? 'https-probe' : 'unknown',
        reason: ['input', 'transport', 'tls', 'size', 'response', 'deadline'].includes(error?.reason) ? error.reason : 'unknown',
        port: [8081, 8188].includes(port) ? port : null };
}
const BOOTSTRAP_CODES = new Set(['TLS_CONFIG_REJECTED', 'LOCAL_SEPARATE_STORES_REQUIRED', 'MULTIHOST_MUST_BE_DISABLED',
    'PLUGINS_MUST_BE_DISABLED', 'EXPLICIT_SAFE_HOSTNAME_REQUIRED', 'UNSUPPORTED_SYSTEM_OPTION', 'UNBOUNDED_DATABASE_OPTIONS',
    'CONTROLLER_VERSION_MISMATCH', 'CONTROLLER_PROFILE_REQUIRED', 'INVALID_CONTROLLER_BASELINE', 'NOT_FRESH_CORE_DATABASE',
    'INVALID_DATABASE_OBJECT', 'EXISTING_RUNTIME_OR_ADAPTERS_FORBIDDEN', 'EXISTING_USERS_FORBIDDEN', 'ORDINARY_SETUP_REQUIRED',
    'INVALID_CORE_OBJECT_TYPE', 'SYSTEM_POLICY_DRIFT', 'REPOSITORY_POLICY_DRIFT', 'ADMIN_ACCOUNT_POLICY_DRIFT',
    'INVALID_BOOTSTRAP_INPUT', 'PLUGIN_STATE_DRIFT', 'BOOTSTRAP_MARKER_MISMATCH', 'BOOTSTRAP_NOT_COMPLETE',
    'HOST_STATE_INVALID', 'CONTROLLER_MUST_BE_STOPPED', 'DATABASE_BACKEND_REJECTED', 'POSTGRESQL_PROFILE_REQUIRED',
    'POSTGRESQL_LOCAL_PROFILE_REQUIRED', 'POSTGRESQL_IDENTITY_SEPARATION', 'SETUP_SETTINGS', 'SETUP_TIMEZONE', 'SETUP_CONFIGURATION']);
// Literal tokens reviewed from bootstrap/enrollment/PG and the authenticated
// R7 license core. Unknown future codes remain generic until explicitly added.
const KNOWN_STAGE_CODES = new Set([
    'MANAGEMENT_ADMIN_LOGIN_FAILED', 'MANAGEMENT_LICENSE_STATUS_FAILED', 'MANAGEMENT_AUTH_DEADLINE',
    'MANAGEMENT_AUTH_TRANSPORT', 'MANAGEMENT_AUTH_TLS', 'MANAGEMENT_AUTH_RESPONSE_LIMIT', 'MANAGEMENT_AUTH_RESPONSE',
    'MANAGEMENT_LOG_LIMIT', 'MANAGEMENT_LOG_BOUNDARY', 'MANAGEMENT_LOG_TRUNCATED', 'MANAGEMENT_PID_DEADLINE', 'MANAGEMENT_RUNTIME_ERROR',
    'ENROLLMENT_ACCOUNTS_SCHEMA', 'ENROLLMENT_ACCOUNT_DRIFT', 'ENROLLMENT_ACCOUNT_MARKER', 'ENROLLMENT_ACCOUNT_ROLES_REQUIRED',
    'ENROLLMENT_ACCOUNT_STATE', 'ENROLLMENT_ADAPTER_NOT_ADMITTED', 'ENROLLMENT_ADMIN_DISABLED', 'ENROLLMENT_ADMIN_DRIFT',
    'ENROLLMENT_ADMIN_PASSWORD', 'ENROLLMENT_ALREADY_ATTEMPTED', 'ENROLLMENT_CONTROLLER_RUNNING', 'ENROLLMENT_CORE_BINDING',
    'ENROLLMENT_FIRST_START', 'ENROLLMENT_FRESH_ADMIN_REQUIRED', 'ENROLLMENT_FRESH_GATE_REQUIRED', 'ENROLLMENT_GROUP_DRIFT',
    'ENROLLMENT_INSTANCE_DRIFT', 'ENROLLMENT_INVITATION_STATE', 'ENROLLMENT_LISTENER_DRIFT', 'ENROLLMENT_MARKER',
    'ENROLLMENT_PACKAGE_IDENTITY', 'ENROLLMENT_PASSWORD_POLICY', 'ENROLLMENT_PASSWORD_REUSED', 'ENROLLMENT_PROFILE_SCOPE',
    'ENROLLMENT_REPOSITORY_DRIFT', 'ENROLLMENT_SERVICE_ACL', 'ENROLLMENT_UI_DRIFT', 'ENROLLMENT_UNEXPECTED_INSTANCE',
    'ENROLLMENT_UNEXPECTED_USER', 'EOS_PG_ACCESS_DENIED', 'EOS_PG_BATCH_LIMIT', 'EOS_PG_CLOSED',
    'EOS_PG_COMMAND_UNSUPPORTED', 'EOS_PG_CONFIG', 'EOS_PG_CONNECTION_FAILED', 'EOS_PG_DATABASE',
    'EOS_PG_DOCUMENT_INVALID', 'EOS_PG_DOCUMENT_LIMIT', 'EOS_PG_DOCUMENT_UNSAFE_KEY', 'EOS_PG_DOMAIN',
    'EOS_PG_EVENT', 'EOS_PG_EVENT_WATERMARK', 'EOS_PG_HOST', 'EOS_PG_KEY',
    'EOS_PG_KEY_LIMIT', 'EOS_PG_KEY_MISSING', 'EOS_PG_LUA_UNSUPPORTED', 'EOS_PG_META_OBJECT_REQUIRED',
    'EOS_PG_OBJECTS_CONNECT_FAILED', 'EOS_PG_OBJECT_ID_INVALID', 'EOS_PG_OBJECT_KEYS_INVALID', 'EOS_PG_OBJECT_NAMESPACE_INVALID',
    'EOS_PG_OPTIONS_INVALID', 'EOS_PG_PASSWORD_AUTH_DISABLED', 'EOS_PG_PATTERN_INVALID', 'EOS_PG_PATTERN_VALUE_INVALID',
    'EOS_PG_PATTERN_WORK_LIMIT', 'EOS_PG_PORT', 'EOS_PG_QUERY_FAILED', 'EOS_PG_READ_LIMIT',
    'EOS_PG_REDIS_SETS_UNSUPPORTED', 'EOS_PG_RENAME', 'EOS_PG_ROLE_DOMAIN', 'EOS_PG_ROLE_PRIVILEGE',
    'EOS_PG_SCHEMA', 'EOS_PG_SCHEMA_BOUNDARY', 'EOS_PG_SCHEMA_GRANTS', 'EOS_PG_STATES_CALLBACK_FAILED',
    'EOS_PG_STATES_CONNECT_FAILED', 'EOS_PG_STATES_DB_UNAVAILABLE', 'EOS_PG_STATES_EVENT_INVALID', 'EOS_PG_STATES_EVENT_LIMIT',
    'EOS_PG_STATES_INVALID_BUFFER', 'EOS_PG_STATES_INVALID_EXPIRY', 'EOS_PG_STATES_INVALID_JSON', 'EOS_PG_STATES_INVALID_KEY',
    'EOS_PG_STATES_INVALID_KEYS', 'EOS_PG_STATES_INVALID_LOG', 'EOS_PG_STATES_INVALID_MESSAGE', 'EOS_PG_STATES_INVALID_NAMESPACE',
    'EOS_PG_STATES_INVALID_STORED_JSON', 'EOS_PG_STATES_MATCH_LIMIT', 'EOS_PG_STATES_NAMESPACE_COLLISION', 'EOS_PG_STATES_NAMESPACE_DENIED',
    'EOS_PG_STATES_PROTOCOL_UNSUPPORTED', 'EOS_PG_STATES_RECONNECT_FAILED', 'EOS_PG_STATES_SUBSCRIPTION_LIMIT', 'EOS_PG_STATES_VALUE_TOO_LARGE',
    'EOS_PG_SUBSCRIPTION_INVALID', 'EOS_PG_SUBSCRIPTION_LIMIT', 'EOS_PG_SUBSCRIPTION_WORK_LIMIT', 'EOS_PG_TLS_CONFIG',
    'EOS_PG_TLS_ENVIRONMENT', 'EOS_PG_TLS_MATERIAL', 'EOS_PG_TLS_NEGOTIATED', 'EOS_PG_TLS_REQUIRED',
    'EOS_PG_TLS_VERSION', 'EOS_PG_TRANSACTION', 'EOS_PG_TRANSACTION_ABORTED', 'EOS_PG_TRANSACTION_FAILED',
    'EOS_PG_TRANSACTION_TIMEOUT', 'EOS_PG_TTL', 'EOS_PG_UNAVAILABLE', 'EOS_PG_UPDATE',
    'EOS_PG_USER', 'EOS_PG_VALUE', 'EOS_PG_VALUE_LIMIT', 'EOS_PG_VIEW_INVALID_INSTANCE_ID',
    'EOS_PG_VIEW_PARAMS_INVALID', 'EOS_PG_VIEW_RANGE_INVALID', 'EOS_PG_VIEW_UNSUPPORTED', 'LICENSE_CLAIMS_INVALID',
    'LICENSE_EXPIRED', 'LICENSE_FORMAT_INVALID', 'LICENSE_KEY_UNKNOWN', 'LICENSE_NOT_YET_VALID',
    'LICENSE_OPTIONS_INVALID', 'LICENSE_SIGNATURE_INVALID', 'LICENSE_TIME_INVALID', 'LICENSE_UUID_INVALID',
    'LICENSE_UUID_MISMATCH', 'LICENSE_VALID', 'MANAGEMENT_CLIENT_FAILED', 'MANAGEMENT_CLIENT_TIMEOUT',
    'MANAGEMENT_CLI_FAILED', 'MANAGEMENT_DEADLINE', 'MANAGEMENT_EXPLICIT_NATIVE_LAB_REQUIRED', 'MANAGEMENT_LICENSE_STORAGE_FAILED',
    'MANAGEMENT_PRIVATE_DATABASE_REQUIRED', 'MANAGEMENT_PRODUCTION_READINESS_FAILED', 'MANAGEMENT_STAGE_FAILED', 'MANAGEMENT_UNEXPECTED_APP_LINK',
    'ONBOARD_ADAPTERS_NOT_READY', 'ONBOARD_ALREADY_PROVISIONED', 'ONBOARD_DATABASE_FAILED', 'ONBOARD_DATABASE_TIMEOUT',
    'ONBOARD_FAILED', 'ONBOARD_HOST_COMMAND', 'ONBOARD_HTTPS_NOT_READY', 'ONBOARD_INPUT_PATH',
    'ONBOARD_READINESS_INPUT', 'ONBOARD_ROOT_REQUIRED', 'ONBOARD_SECRET_PERMISSIONS', 'ONBOARD_SNAPSHOT_CHANGED',
    'ONBOARD_START_BLOCK_FAILED', 'ONBOARD_STOP_FAILED', 'ONBOARD_TIMEOUT', 'ONBOARD_USAGE',
    'STORAGE_AUTH_FAILED', 'STORAGE_CLOCK_ROLLBACK', 'STORAGE_DATA_INVALID', 'STORAGE_DIRECTORY_INVALID',
    'STORAGE_FORMAT_INVALID', 'STORAGE_IO_ERROR', 'STORAGE_KEY_INVALID', 'STORAGE_KEY_MISSING',
    'STORAGE_SIZE_INVALID', 'STORAGE_UNSAFE_PATH', 'TRUST_INVALID', 'WEB_CERTIFICATE_CA',
    'WEB_CERTIFICATE_CA_KEY_MISMATCH', 'WEB_CERTIFICATE_CA_KEY_PERMISSIONS', 'WEB_CERTIFICATE_CA_ROTATION_REQUIRED', 'WEB_CERTIFICATE_FAILED',
    'WEB_CERTIFICATE_HOSTS', 'WEB_CERTIFICATE_INVALID', 'WEB_CERTIFICATE_KEY_PERMISSIONS', 'WEB_CERTIFICATE_MANIFEST',
    'WEB_CERTIFICATE_OPENSSL', 'WEB_CERTIFICATE_PATH', 'WEB_CERTIFICATE_PROBE_IDENTITY', 'WEB_CERTIFICATE_PROBE_PORTS',
    'WEB_CERTIFICATE_PROBE_REJECTED', 'WEB_CERTIFICATE_PROBE_TIMEOUT', 'WEB_CERTIFICATE_ROOT_REQUIRED', 'WEB_CERTIFICATE_SAN',
    'WEB_CERTIFICATE_SETUP_EXISTS', 'WEB_CERTIFICATE_TIME',
]);
function stageFailure(error) {
    const code = error?.code || error?.message;
    if (BOOTSTRAP_CODES.has(code)) return code;
    if (KNOWN_STAGE_CODES.has(code)) return code;
    if (code === 'ERR_ASSERTION') return 'MANAGEMENT_ASSERTION_FAILED';
    if (['EACCES', 'EPERM', 'EROFS', 'ENOENT', 'EEXIST'].includes(code)) return 'MANAGEMENT_FS_' + code;
    if (code === 'permissionError') return 'MANAGEMENT_DB_PERMISSION_DENIED';
    if (error?.name === 'TypeError') return 'MANAGEMENT_TYPE_ERROR';
    if (error?.name === 'ReferenceError') return 'MANAGEMENT_REFERENCE_ERROR';
    return 'MANAGEMENT_STAGE_FAILED';
}
module.exports = { probeFailure, stageFailure };
